FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

EXPOSE 3333

CMD ["npm", "start"]

# agora para construir o container use isso:
    # sudo docker build -t "nome-imagem" .
    # obs substitua o "nome-imagem" para o nome da imagem, normalmente node-app. SEM AS ASPAS

# e para rodar o container:
    #sudo docker run -p 3333:3333 "nome-imagem"
    # obs subistuir o "nome-imagem" para o nome da imagem criada. SEM AS ASPAS

    # se der certo deu certo :)
# sudo nao usa no windows
